SET session_replication_role = 'replica';
SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;
INSERT INTO peps.module (idmodule, nom, ip_adress, status, volume, current_mode, actif, last_seen, owner_role, version) VALUES (6, 'Module Cage Principale', '192.168.3.12', 'actif', 85, 'Automatique', true, '2026-01-21 15:23:40.923426', 'aras', 0);
INSERT INTO peps.module (idmodule, nom, ip_adress, status, volume, current_mode, actif, last_seen, owner_role, version) VALUES (5, 'Module Perchoir Ara', '192.168.3.11', 'actif', 60, 'Manuel', true, '2026-01-21 15:53:44.659', 'aras', 0);
INSERT INTO peps.module (idmodule, nom, ip_adress, status, volume, current_mode, actif, last_seen, owner_role, version) VALUES (7, 'GESTION ARAS', '192.168.1.1', 'inactif', 50, 'Manuel', false, '2026-01-21 15:36:34.174', 'aras', 0);
INSERT INTO peps.module (idmodule, nom, ip_adress, status, volume, current_mode, actif, last_seen, owner_role, version) VALUES (8, 'test', '192.158.1.100', 'actif', 50, 'Automatique', true, '2026-01-22 09:28:29.991', 'aras', 0);
INSERT INTO peps.module (idmodule, nom, ip_adress, status, volume, current_mode, actif, last_seen, owner_role, version) VALUES (18, 'test_solution_1', '123.123.123.123', 'inactif', 50, 'Manuel', false, '2026-01-24 14:14:20.584', 'aras', 0);
INSERT INTO peps.module (idmodule, nom, ip_adress, status, volume, current_mode, actif, last_seen, owner_role, version) VALUES (19, 'test_solution_2', '111.111.111.111', 'inactif', 50, 'Manuel', false, '2026-01-24 14:17:07.199', 'dauphin', 0);
INSERT INTO peps.module (idmodule, nom, ip_adress, status, volume, current_mode, actif, last_seen, owner_role, version) VALUES (20, 'test_1_for_admin', '111.111.111.111', 'inactif', 50, 'Manuel', false, '2026-01-24 14:41:04.23', 'dauphin', 0);
INSERT INTO peps.module (idmodule, nom, ip_adress, status, volume, current_mode, actif, last_seen, owner_role, version) VALUES (21, 'test_2_for_admin', '111.111.111.111', 'inactif', 50, 'Manuel', false, '2026-01-24 14:41:41.938', 'aras', 0);
INSERT INTO peps.module (idmodule, nom, ip_adress, status, volume, current_mode, actif, last_seen, owner_role, version) VALUES (22, 'test_mock_module_for_admin', '111.111.111.111', 'actif', 50, 'Manuel', true, '2026-01-24 14:50:48.066', 'mock', 0);
INSERT INTO peps.module (idmodule, nom, ip_adress, status, volume, current_mode, actif, last_seen, owner_role, version) VALUES (25, 'alaa', '321.132.312.3', 'actif', 50, 'Manuel', true, '2026-01-25 16:52:39.783', 'mock', 0);
INSERT INTO peps.module (idmodule, nom, ip_adress, status, volume, current_mode, actif, last_seen, owner_role, version) VALUES (26, 'arasee', '412.313.31.6', 'inactif', 50, 'Manuel', false, '2026-01-25 16:53:07.402', 'aras', 0);
INSERT INTO peps.module (idmodule, nom, ip_adress, status, volume, current_mode, actif, last_seen, owner_role, version) VALUES (4, 'Module Volière Ara', '192.168.3.10', 'actif', 75, 'Automatique', true, '2026-01-30 11:10:19.392', 'aras', 0);
INSERT INTO peps.module (idmodule, nom, ip_adress, status, volume, current_mode, actif, last_seen, owner_role, version) VALUES (1, 'Module Bassin Principal', '192.168.2.10', 'actif', 90, 'Automatique', true, '2026-01-21 15:23:40.923426', 'dauphin', 0);
INSERT INTO peps.module (idmodule, nom, ip_adress, status, volume, current_mode, actif, last_seen, owner_role, version) VALUES (2, 'Module Zone Repos', '192.168.2.11', 'actif', 50, 'Manuel', true, '2026-01-21 15:13:40.923426', 'dauphin', 0);
INSERT INTO peps.module (idmodule, nom, ip_adress, status, volume, current_mode, actif, last_seen, owner_role, version) VALUES (3, 'Module Piscine Entrainement', '192.168.2.12', 'actif', 70, 'Automatique', true, '2026-01-21 15:27:40.923426', 'dauphin', 0);
INSERT INTO peps.sound (idsound, nom, type_son, extension, chemin, owner_role, version) VALUES (6, 'Cri Ara Bleu', 'Vocal', 'mp3', NULL, 'aras', 0);
INSERT INTO peps.sound (idsound, nom, type_son, extension, chemin, owner_role, version) VALUES (7, 'Musique Tropicale', 'Ambiance', 'mp3', NULL, 'aras', 0);
INSERT INTO peps.sound (idsound, nom, type_son, extension, chemin, owner_role, version) VALUES (8, 'Pluie Amazonienne', 'Naturel', 'wav', NULL, 'aras', 0);
INSERT INTO peps.sound (idsound, nom, type_son, extension, chemin, owner_role, version) VALUES (9, 'Chant Perroquet', 'Vocal', 'mp3', NULL, 'aras', 0);
INSERT INTO peps.sound (idsound, nom, type_son, extension, chemin, owner_role, version) VALUES (10, 'Foret Tropicale', 'Ambiance', 'wav', NULL, 'aras', 0);
INSERT INTO peps.sound (idsound, nom, type_son, extension, chemin, owner_role, version) VALUES (11, 'estrydgiuh', 'Ambiance', 'mp3', 'sons\Ambiance\estrydgiuh_1769068885707.mp3', 'aras', 0);
INSERT INTO peps.sound (idsound, nom, type_son, extension, chemin, owner_role, version) VALUES (19, 'test_solution_1', 'Naturel', 'mp3', 'sons\Naturel\test_solution_1_1769260864176.mp3', 'aras', 0);
INSERT INTO peps.sound (idsound, nom, type_son, extension, chemin, owner_role, version) VALUES (20, 'test_solution_2', 'Naturel', 'mp3', 'sons\Naturel\test_solution_2_1769260905961.mp3', 'dauphin', 0);
INSERT INTO peps.sound (idsound, nom, type_son, extension, chemin, owner_role, version) VALUES (21, 'test_sound_1_for_admin', 'Naturel', 'mp3', 'sons\Naturel\test_sound_1_for_admin_1769262263429.mp3', 'dauphin', 0);
INSERT INTO peps.sound (idsound, nom, type_son, extension, chemin, owner_role, version) VALUES (22, 'test_sound_2_for_admin', 'Ambiance', 'mp3', 'sons\Ambiance\test_sound_2_for_admin_1769262286852.mp3', 'aras', 0);
INSERT INTO peps.sound (idsound, nom, type_son, extension, chemin, owner_role, version) VALUES (23, 'test_sound_mock_for_admin', 'Ambiance', 'mp3', 'sons\Ambiance\test_sound_mock_for_admin_1769262608864.mp3', 'mock', 0);
INSERT INTO peps.sound (idsound, nom, type_son, extension, chemin, owner_role, version) VALUES (24, 'zzfz', 'Vocal', 'm4a', 'sons\Vocal\zzfz_1769768160048.m4a', 'aras', 0);
INSERT INTO peps.sound (idsound, nom, type_son, extension, chemin, owner_role, version) VALUES (25, 'sss', 'Ambiance', 'm4a', 'sons\Ambiance\sss_1769768333999.m4a', 'aras', 0);
INSERT INTO peps.sound (idsound, nom, type_son, extension, chemin, owner_role, version) VALUES (26, 'aa', 'Vocal', 'mp3', 'sons\Vocal\aa_1769768357691.mp3', 'tester', 0);
INSERT INTO peps.sound (idsound, nom, type_son, extension, chemin, owner_role, version) VALUES (27, 'ddd', 'Vocal', 'mp3', 'sons\Vocal\ddd_1769768606838.mp3', 'aras', 0);
INSERT INTO peps.sound (idsound, nom, type_son, extension, chemin, owner_role, version) VALUES (2, 'Clics de Dauphin', 'Vocal', 'wav', NULL, 'dauphin', 0);
INSERT INTO peps.sound (idsound, nom, type_son, extension, chemin, owner_role, version) VALUES (3, 'Vagues Océan', 'Ambiance', 'mp3', NULL, 'dauphin', 0);
INSERT INTO peps.sound (idsound, nom, type_son, extension, chemin, owner_role, version) VALUES (4, 'Sonar Marin', 'Vocal', 'mp3', NULL, 'dauphin', 0);
INSERT INTO peps.sound (idsound, nom, type_son, extension, chemin, owner_role, version) VALUES (5, 'Musique Aquatique', 'Ambiance', 'wav', NULL, 'dauphin', 0);
INSERT INTO peps.sound (idsound, nom, type_son, extension, chemin, owner_role, version) VALUES (1, 'Chant des Baleines', 'Naturelle', 'mp3', NULL, 'dauphin', 0);
INSERT INTO peps.interaction (idinteraction, idsound, idmodule, typeinteraction, time_lancement, owner_role) VALUES (1, 1, 1, 'Head', '2026-01-21 15:18:40.923426', 'dauphin');
INSERT INTO peps.interaction (idinteraction, idsound, idmodule, typeinteraction, time_lancement, owner_role) VALUES (2, 2, 1, 'Tail', '2026-01-21 15:20:40.923426', 'dauphin');
INSERT INTO peps.interaction (idinteraction, idsound, idmodule, typeinteraction, time_lancement, owner_role) VALUES (3, 6, 4, 'Bec', '2026-01-21 15:08:40.923426', 'aras');
INSERT INTO peps.interaction (idinteraction, idsound, idmodule, typeinteraction, time_lancement, owner_role) VALUES (4, 7, 5, 'Patte', '2026-01-21 15:13:40.923426', 'aras');
INSERT INTO peps.interaction (idinteraction, idsound, idmodule, typeinteraction, time_lancement, owner_role) VALUES (5, 1, 1, 'Head', '2026-01-25 09:15:00', 'dauphin');
INSERT INTO peps.interaction (idinteraction, idsound, idmodule, typeinteraction, time_lancement, owner_role) VALUES (6, 2, 1, 'Tail', '2026-01-25 14:30:00', 'dauphin');
INSERT INTO peps.interaction (idinteraction, idsound, idmodule, typeinteraction, time_lancement, owner_role) VALUES (7, 6, 4, 'Bec', '2026-01-25 16:45:00', 'aras');
INSERT INTO peps.interaction (idinteraction, idsound, idmodule, typeinteraction, time_lancement, owner_role) VALUES (8, 7, 5, 'Patte', '2026-01-24 10:00:00', 'aras');
INSERT INTO peps.interaction (idinteraction, idsound, idmodule, typeinteraction, time_lancement, owner_role) VALUES (9, 1, 1, 'Head', '2026-01-24 18:20:00', 'dauphin');
INSERT INTO peps.interaction (idinteraction, idsound, idmodule, typeinteraction, time_lancement, owner_role) VALUES (10, 2, 1, 'Tail', '2026-01-22 11:00:00', 'dauphin');
INSERT INTO peps.interaction (idinteraction, idsound, idmodule, typeinteraction, time_lancement, owner_role) VALUES (11, 6, 4, 'Bec', '2026-01-22 15:30:00', 'aras');
INSERT INTO peps.interaction (idinteraction, idsound, idmodule, typeinteraction, time_lancement, owner_role) VALUES (12, 1, 1, 'Head', '2026-01-10 09:00:00', 'dauphin');
INSERT INTO peps.interaction (idinteraction, idsound, idmodule, typeinteraction, time_lancement, owner_role) VALUES (13, 7, 5, 'Patte', '2026-01-10 13:45:00', 'aras');
INSERT INTO peps.interaction (idinteraction, idsound, idmodule, typeinteraction, time_lancement, owner_role) VALUES (14, 1, 1, 'Head', '2025-12-25 10:00:00', 'dauphin');
INSERT INTO peps.interaction (idinteraction, idsound, idmodule, typeinteraction, time_lancement, owner_role) VALUES (15, NULL, 1, 'TEST_PAGIN_Y08', '2026-01-24 08:00:00', 'dauphin');
INSERT INTO peps.interaction (idinteraction, idsound, idmodule, typeinteraction, time_lancement, owner_role) VALUES (16, NULL, 1, 'TEST_PAGIN_Y09', '2026-01-24 09:15:00', 'dauphin');
INSERT INTO peps.interaction (idinteraction, idsound, idmodule, typeinteraction, time_lancement, owner_role) VALUES (17, NULL, 1, 'TEST_PAGIN_Y10', '2026-01-24 10:30:00', 'dauphin');
INSERT INTO peps.interaction (idinteraction, idsound, idmodule, typeinteraction, time_lancement, owner_role) VALUES (18, NULL, 1, 'TEST_PAGIN_Y11', '2026-01-24 11:45:00', 'dauphin');
INSERT INTO peps.interaction (idinteraction, idsound, idmodule, typeinteraction, time_lancement, owner_role) VALUES (19, NULL, 1, 'TEST_PAGIN_Y12', '2026-01-24 12:00:00', 'dauphin');
INSERT INTO peps.interaction (idinteraction, idsound, idmodule, typeinteraction, time_lancement, owner_role) VALUES (20, NULL, 1, 'TEST_PAGIN_Y13', '2026-01-24 13:15:00', 'dauphin');
INSERT INTO peps.interaction (idinteraction, idsound, idmodule, typeinteraction, time_lancement, owner_role) VALUES (21, NULL, 1, 'TEST_PAGIN_Y14', '2026-01-24 14:30:00', 'dauphin');
INSERT INTO peps.interaction (idinteraction, idsound, idmodule, typeinteraction, time_lancement, owner_role) VALUES (22, NULL, 1, 'TEST_PAGIN_Y15', '2026-01-24 15:45:00', 'dauphin');
INSERT INTO peps.interaction (idinteraction, idsound, idmodule, typeinteraction, time_lancement, owner_role) VALUES (23, NULL, 1, 'TEST_PAGIN_Y16', '2026-01-24 16:00:00', 'dauphin');
INSERT INTO peps.interaction (idinteraction, idsound, idmodule, typeinteraction, time_lancement, owner_role) VALUES (24, NULL, 1, 'TEST_PAGIN_Y17', '2026-01-24 17:30:00', 'dauphin');
INSERT INTO peps.interaction (idinteraction, idsound, idmodule, typeinteraction, time_lancement, owner_role) VALUES (25, NULL, 1, 'TEST_PAGIN_08', '2026-01-25 08:00:00', 'dauphin');
INSERT INTO peps.interaction (idinteraction, idsound, idmodule, typeinteraction, time_lancement, owner_role) VALUES (26, NULL, 1, 'TEST_PAGIN_09', '2026-01-25 09:15:00', 'dauphin');
INSERT INTO peps.interaction (idinteraction, idsound, idmodule, typeinteraction, time_lancement, owner_role) VALUES (27, NULL, 1, 'TEST_PAGIN_10', '2026-01-25 10:30:00', 'dauphin');
INSERT INTO peps.interaction (idinteraction, idsound, idmodule, typeinteraction, time_lancement, owner_role) VALUES (28, NULL, 1, 'TEST_PAGIN_11', '2026-01-25 11:45:00', 'dauphin');
INSERT INTO peps.interaction (idinteraction, idsound, idmodule, typeinteraction, time_lancement, owner_role) VALUES (29, NULL, 1, 'TEST_PAGIN_12', '2026-01-25 12:00:00', 'dauphin');
INSERT INTO peps.interaction (idinteraction, idsound, idmodule, typeinteraction, time_lancement, owner_role) VALUES (30, NULL, 1, 'TEST_PAGIN_13', '2026-01-25 13:15:00', 'dauphin');
INSERT INTO peps.interaction (idinteraction, idsound, idmodule, typeinteraction, time_lancement, owner_role) VALUES (31, NULL, 1, 'TEST_PAGIN_14', '2026-01-25 14:30:00', 'dauphin');
INSERT INTO peps.interaction (idinteraction, idsound, idmodule, typeinteraction, time_lancement, owner_role) VALUES (32, NULL, 1, 'TEST_PAGIN_15', '2026-01-25 15:45:00', 'dauphin');
INSERT INTO peps.interaction (idinteraction, idsound, idmodule, typeinteraction, time_lancement, owner_role) VALUES (33, NULL, 1, 'TEST_PAGIN_16', '2026-01-25 16:00:00', 'dauphin');
INSERT INTO peps.interaction (idinteraction, idsound, idmodule, typeinteraction, time_lancement, owner_role) VALUES (34, NULL, 1, 'TEST_PAGIN_17', '2026-01-25 17:30:00', 'dauphin');
INSERT INTO peps.interaction (idinteraction, idsound, idmodule, typeinteraction, time_lancement, owner_role) VALUES (35, NULL, 19, 'Head', '2025-08-15 10:30:00', 'dauphin');
INSERT INTO peps.interaction (idinteraction, idsound, idmodule, typeinteraction, time_lancement, owner_role) VALUES (36, NULL, 19, 'Tail', '2025-09-10 14:45:00', 'dauphin');
INSERT INTO peps.interaction (idinteraction, idsound, idmodule, typeinteraction, time_lancement, owner_role) VALUES (37, NULL, 19, 'Head', '2025-10-05 09:15:00', 'dauphin');
INSERT INTO peps.interaction (idinteraction, idsound, idmodule, typeinteraction, time_lancement, owner_role) VALUES (38, NULL, 4, 'Bec', '2025-08-20 11:00:00', 'aras');
INSERT INTO peps.interaction (idinteraction, idsound, idmodule, typeinteraction, time_lancement, owner_role) VALUES (39, NULL, 4, 'Patte', '2025-09-25 16:30:00', 'aras');
INSERT INTO peps.interaction (idinteraction, idsound, idmodule, typeinteraction, time_lancement, owner_role) VALUES (40, NULL, 4, 'Bec', '2025-10-15 08:45:00', 'aras');
INSERT INTO peps.interaction (idinteraction, idsound, idmodule, typeinteraction, time_lancement, owner_role) VALUES (41, NULL, 19, 'Tail', '2025-05-12 13:20:00', 'dauphin');
INSERT INTO peps.interaction (idinteraction, idsound, idmodule, typeinteraction, time_lancement, owner_role) VALUES (42, NULL, 19, 'Head', '2025-06-18 15:00:00', 'dauphin');
INSERT INTO peps.interaction (idinteraction, idsound, idmodule, typeinteraction, time_lancement, owner_role) VALUES (43, NULL, 19, 'Tail', '2025-07-22 10:10:00', 'dauphin');
INSERT INTO peps.interaction (idinteraction, idsound, idmodule, typeinteraction, time_lancement, owner_role) VALUES (44, NULL, 4, 'Patte', '2025-05-08 09:30:00', 'aras');
INSERT INTO peps.interaction (idinteraction, idsound, idmodule, typeinteraction, time_lancement, owner_role) VALUES (45, NULL, 4, 'Bec', '2025-06-25 11:45:00', 'aras');
INSERT INTO peps.interaction (idinteraction, idsound, idmodule, typeinteraction, time_lancement, owner_role) VALUES (46, NULL, 4, 'Patte', '2025-07-30 14:15:00', 'aras');
INSERT INTO peps.users (id, login, roles, password, email) VALUES (8, 'Haytam', '[]', '$2y$13$scNBACUxkGfjhUWs8hEX7uVNB42Ek3d8ZaEqc2Xw89syOg7OiLFlq', 'haytam.bensribit@gmail.com');
INSERT INTO peps.users (id, login, roles, password, email) VALUES (9, 'admin', '[]', '$2y$13$OKlzoqquC9Qui1V/NoLszO.QceJr70LaR8DdKgqZIG2Taqm2KaiPm', 'haytam.bensribit@gmail.com');
INSERT INTO peps.users (id, login, roles, password, email) VALUES (10, 'admind', '[]', '$2y$13$Wmld0i8t3asztgTSAROUwOIY.6nz/HDX.skHdTNtwgL/5Fcm5Q7Wu', 'haytam.bensribit@gmail.com');
SELECT pg_catalog.setval('peps.audit_logs_id_seq', 30, true);
SELECT pg_catalog.setval('peps.interaction_idinteraction_seq', 58, true);
SELECT pg_catalog.setval('peps.module_idmodule_seq', 27, true);
SELECT pg_catalog.setval('peps.sound_idsound_seq', 27, true);
SELECT pg_catalog.setval('peps.users_id_user_seq', 23, true);
SELECT pg_catalog.setval('peps.book_id_seq', 11, true);
SELECT pg_catalog.setval('peps.borrow_id_seq', 20, true);
SELECT pg_catalog.setval('peps.messenger_messages_id_seq', 7, true);
SELECT pg_catalog.setval('peps.person_id_seq', 13, true);
SELECT pg_catalog.setval('peps.users_id_user_seq', 10, true);
